package com.example.model

/**
 * Represents a virtual camera framing keyframe in normalized coordinates [0..1] with zoom level.
 */
data class CameraKeyframe(
    val timestampMs: Long,
    val focusX: Float = 0.5f,     // Normalized horizontal center of virtual camera [0..1]
    val focusY: Float = 0.5f,     // Normalized vertical center of virtual camera [0..1]
    val zoom: Float = 1.0f,       // Zoom magnification (1.0x to 10.0x)
    val isAutoGenerated: Boolean = true
)

/**
 * Settings for AI-driven virtual camera movement.
 */
data class CameraMotionConfig(
    val autoFollow: Boolean = true,
    val autoZoom: Boolean = true,
    val trackingSensitivity: Float = 0.80f, // 0.0 - 1.0
    val smoothness: Float = 0.85f,          // 0.0 - 1.0 (higher = smoother cinematic dampening)
    val deadZone: Float = 0.15f,            // 0.0 - 1.0 (tolerance box before camera follows)
    val maxZoom: Float = 3.5f,              // 1.0 - 10.0
    val minZoom: Float = 1.0f,              // 1.0
    val followStrength: Float = 0.90f,      // 0.0 - 1.0
    val zoomSmoothness: Float = 0.80f,      // 0.0 - 1.0
    val verticalFollow: Boolean = true,
    val horizontalFollow: Boolean = true
)
