package com.example.ai

import android.graphics.PointF
import com.example.model.CameraKeyframe
import com.example.model.CameraMotionConfig
import com.example.model.PoseFrameData
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min

class VirtualCameraController {

    private var currentCameraX = 0.5f
    private var currentCameraY = 0.5f
    private var currentZoom = 1.0f

    private var velocityX = 0f
    private var velocityY = 0f
    private var velocityZoom = 0f

    /**
     * Updates virtual camera position for a single frame given the target pose data and configuration.
     */
    fun updateFrame(
        pose: PoseFrameData?,
        config: CameraMotionConfig,
        dtSeconds: Float = 0.033f
    ): CameraKeyframe {
        if (!config.autoFollow && !config.autoZoom) {
            return CameraKeyframe(
                timestampMs = pose?.timestampMs ?: 0L,
                focusX = currentCameraX,
                focusY = currentCameraY,
                zoom = currentZoom,
                isAutoGenerated = true
            )
        }

        // Target position defaults to center if not detected
        val targetX = if (config.horizontalFollow && pose != null) pose.centerOfMassX else 0.5f
        // Offset Y slightly above center of mass so head and chest are well framed in camera viewport
        val targetY = if (config.verticalFollow && pose != null) {
            val head = pose.headCenter
            if (head != null) {
                (head.y * 0.4f + pose.centerOfMassY * 0.6f).coerceIn(0.1f, 0.9f)
            } else {
                pose.centerOfMassY
            }
        } else 0.5f

        // Target Zoom based on bounding box size
        val targetZoom = if (config.autoZoom && pose != null) {
            val boxHeight = pose.boundingBox.height()
            val boxWidth = pose.boundingBox.width()
            val maxSpan = max(boxHeight, boxWidth)
            if (maxSpan > 0.05f) {
                // Ideal framing spans ~60% of viewport height
                val idealZoom = (0.60f / maxSpan) * config.followStrength
                idealZoom.coerceIn(config.minZoom, config.maxZoom)
            } else {
                config.minZoom
            }
        } else {
            currentZoom
        }

        // Dead Zone filtering: only move if outside dead zone threshold
        val diffX = targetX - currentCameraX
        val diffY = targetY - currentCameraY
        val deadZoneRadius = config.deadZone * 0.25f // scaled dead zone

        val effectiveDiffX = if (abs(diffX) > deadZoneRadius) {
            diffX - (if (diffX > 0) deadZoneRadius else -deadZoneRadius)
        } else 0f

        val effectiveDiffY = if (abs(diffY) > deadZoneRadius) {
            diffY - (if (diffY > 0) deadZoneRadius else -deadZoneRadius)
        } else 0f

        // Smoothing factor (0 = snappy, 1 = heavy cinematic dampening)
        val alpha = (1.0f - config.smoothness * 0.9f).coerceIn(0.05f, 0.95f) * config.trackingSensitivity
        val zoomAlpha = (1.0f - config.zoomSmoothness * 0.9f).coerceIn(0.05f, 0.95f)

        // Spring / Damping motion update
        velocityX = (velocityX * 0.7f + effectiveDiffX * alpha * (1f / dtSeconds) * 0.1f)
        velocityY = (velocityY * 0.7f + effectiveDiffY * alpha * (1f / dtSeconds) * 0.1f)

        // Clamp max camera speed to prevent abrupt jerks
        val maxSpeed = 1.8f // max screens per second
        velocityX = velocityX.coerceIn(-maxSpeed, maxSpeed)
        velocityY = velocityY.coerceIn(-maxSpeed, maxSpeed)

        currentCameraX = (currentCameraX + velocityX * dtSeconds).coerceIn(0.1f, 0.9f)
        currentCameraY = (currentCameraY + velocityY * dtSeconds).coerceIn(0.1f, 0.9f)

        // Zoom smoothing
        val diffZoom = targetZoom - currentZoom
        velocityZoom = velocityZoom * 0.75f + diffZoom * zoomAlpha * (1f / dtSeconds) * 0.08f
        currentZoom = (currentZoom + velocityZoom * dtSeconds).coerceIn(config.minZoom, config.maxZoom)

        return CameraKeyframe(
            timestampMs = pose?.timestampMs ?: 0L,
            focusX = currentCameraX,
            focusY = currentCameraY,
            zoom = currentZoom,
            isAutoGenerated = true
        )
    }

    /**
     * Evaluates the interpolated camera keyframe at any given timestamp from a list of keyframes.
     */
    fun evaluateKeyframeAt(timestampMs: Long, keyframes: List<CameraKeyframe>): CameraKeyframe {
        if (keyframes.isEmpty()) {
            return CameraKeyframe(timestampMs, 0.5f, 0.5f, 1.0f)
        }
        if (keyframes.size == 1 || timestampMs <= keyframes.first().timestampMs) {
            return keyframes.first().copy(timestampMs = timestampMs)
        }
        if (timestampMs >= keyframes.last().timestampMs) {
            return keyframes.last().copy(timestampMs = timestampMs)
        }

        // Find surrounding keyframes
        var k0 = keyframes[0]
        var k1 = keyframes[1]
        for (i in 0 until keyframes.size - 1) {
            if (timestampMs >= keyframes[i].timestampMs && timestampMs <= keyframes[i + 1].timestampMs) {
                k0 = keyframes[i]
                k1 = keyframes[i + 1]
                break
            }
        }

        val totalSpan = (k1.timestampMs - k0.timestampMs).toFloat()
        if (totalSpan <= 0f) return k0.copy(timestampMs = timestampMs)

        val t = ((timestampMs - k0.timestampMs) / totalSpan).coerceIn(0f, 1f)

        // Smooth cubic ease (Hermite s-curve: 3t^2 - 2t^3)
        val smoothT = t * t * (3f - 2f * t)

        val interpX = k0.focusX + (k1.focusX - k0.focusX) * smoothT
        val interpY = k0.focusY + (k1.focusY - k0.focusY) * smoothT
        val interpZoom = k0.zoom + (k1.zoom - k0.zoom) * smoothT

        return CameraKeyframe(
            timestampMs = timestampMs,
            focusX = interpX.coerceIn(0.05f, 0.95f),
            focusY = interpY.coerceIn(0.05f, 0.95f),
            zoom = interpZoom.coerceIn(1.0f, 10.0f),
            isAutoGenerated = false
        )
    }

    fun reset() {
        currentCameraX = 0.5f
        currentCameraY = 0.5f
        currentZoom = 1.0f
        velocityX = 0f
        velocityY = 0f
        velocityZoom = 0f
    }
}
